// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("DAL.Rectangle", b =>
                {
                    b.Property<int>("RectangleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxX")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxY")
                        .HasColumnType("REAL");

                    b.Property<double>("MinX")
                        .HasColumnType("REAL");

                    b.Property<double>("MinY")
                        .HasColumnType("REAL");

                    b.HasKey("RectangleId");

                    b.HasIndex("MinX", "MinY", "MaxX", "MaxY");

                    b.ToTable("Rectangles");
                });
#pragma warning restore 612, 618
        }
    }
}
